[package]
description = "Common markers and types for kenobi"
name = "kenobi-core"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
native-tls = { version = "0.2.18", optional = true }

[features]
native-tls = ["dep:native-tls"]
